cc_library(
    name = "obl_primitives",
    srcs = [],
    hdrs = [
        "obl_primitives.h"
    ],
    deps = [
    ],
)

cc_test(
    name = "obl_primitives_test",
    srcs = [ "obl_primitives_test.cc" ],
    deps = [
        ":obl_primitives",
        "@com_google_googletest//:gtest_main"
    ],
    linkstatic = True,
)
